### ISSUE TITLE
HostRegisterActivity与TargetAppCompatActivity的区别是什么

### ISSUE THREAD

**Issue by tkkcc** [androidmalin/AndroidComponentPlugin#12]
HostRegisterActivity和TargetAppCompatActivity都没在manifest中体现，请问为什么前者是注册的，后者是未注册的。

**Comment by androidmalin** [comment]
感谢反馈，名字起的有歧义，HostRegisterActivity表示的应该是，宿主apk中存在的未注册的activity。TargetAppCompatActivity：表示插件apk 中的activity

**Comment by tkkcc** [comment]
TargetAppCompatActivity我指的是这个
https://github.com/androidmalin/AndroidComponentPlugin/blob/develop_kotlin/app/src/main/java/com/malin/hook/MainActivity.kt#L112
应该也是存在于宿主apk中且未注册的吧，所以和HostRegisterActivity想表达的能力一样呢我感觉

**Comment by androidmalin** [comment]
是的，你理解的是对的。

**Comment by tkkcc** [comment]
好的，感谢
